# Generated by Django 4.1.4 on 2023-02-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventUp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
