# Generated by Django 4.1.4 on 2023-02-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventUp', '0006_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='HI', max_length=50),
            preserve_default=False,
        ),
    ]
