# Generated by Django 4.1.4 on 2023-02-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventUp', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
