# Generated by Django 4.1.4 on 2023-02-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventUp', '0013_profile_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
