# Generated by Django 4.1.4 on 2023-02-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventUp', '0020_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
