# Generated by Django 4.1.4 on 2023-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventUp', '0023_alter_comment_content_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
