# Generated by Django 4.1.4 on 2023-02-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventUp', '0024_alter_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='brr', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
