# Generated by Django 4.1.4 on 2023-02-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventUp', '0025_event_link_event_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
